package com.springrs.plugin.codegen

import com.intellij.database.model.DasTable
import com.intellij.database.util.DasUtil
import com.springrs.plugin.codegen.dialect.DatabaseDialect

/**
 * Reads table metadata from IntelliJ Database Tools API (DasTable).
 *
 * Uses [DatabaseDialect] for database-specific SQL → Rust type mapping.
 */
object TableMetadataReader {

    /**
     * Read metadata for a single table, auto-detecting the database dialect.
     */
    fun readTable(table: DasTable): TableInfo {
        val dialect = DatabaseDialect.detect(table)
        return readTable(table, dialect)
    }

    /**
     * Read metadata for a single table using the specified dialect.
     */
    fun readTable(
        table: DasTable,
        dialect: DatabaseDialect,
        tableNamePrefix: String = "",
        columnNamePrefix: String = ""
    ): TableInfo {
        val primaryKeyNames = mutableListOf<String>()
        DasUtil.getPrimaryKey(table)?.let { pk ->
            pk.columnsRef.names().forEach { primaryKeyNames.add(it) }
        }

        val columns = mutableListOf<ColumnInfo>()
        for (col in DasUtil.getColumns(table)) {
            @Suppress("DEPRECATION")
            val sqlType = col.dataType.typeName
            val isPk = col.name in primaryKeyNames
            val isNullable = !col.isNotNull && !isPk
            val isAutoIncrement = DasUtil.isAutoGenerated(col)

            columns.add(
                ColumnInfo(
                    name = col.name,
                    sqlType = sqlType,
                    rustType = dialect.toRustType(sqlType),
                    isPrimaryKey = isPk,
                    isNullable = isNullable,
                    isAutoIncrement = isAutoIncrement,
                    comment = col.comment,
                    defaultValue = col.default
                )
            )
        }

        return TableInfo(
            name = table.name,
            comment = table.comment,
            columns = columns,
            primaryKeys = primaryKeyNames,
            tableNamePrefix = tableNamePrefix,
            columnNamePrefix = columnNamePrefix
        )
    }

    /**
     * Read metadata for multiple tables, auto-detecting dialect from the first table.
     */
    fun readTables(tables: List<DasTable>): List<TableInfo> {
        if (tables.isEmpty()) return emptyList()
        val dialect = DatabaseDialect.detect(tables.first())
        return tables.map { readTable(it, dialect) }
    }
}
